#:kivy 2.0

BoxLayoutExample:

<BoxLayoutExample>:
  orientation: "vertical"

  Label:
    text: "Stopwatch"

  Label:
    id: clock_label
    text: "Clock goes here"

  BoxLayout:

    Button:
      id: start_button
      text: "Start"
      on_press: root.start_clock()

    Button:
      id: stop_button
      text: "Stop"
      on_press: root.pause_clock()
      disabled: True

    Button:
      id: reset_button
      text: "Reset"
      on_press: root.reset_clock()
